log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out

router bgp 5
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.17 remote-as 2
	neighbor 192.0.2.42 remote-as 8
	neighbor 192.0.2.43 remote-as 9
