log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out

router bgp 2

	! disable requirement of filtering policy
	no bgp ebgp-requires-policy

	! declare neighboring AS
	neighbor 192.0.2.5 remote-as 1
	neighbor 192.0.2.10 remote-as 3

	! IPv4 config
	address-family ipv4 unicast
		neighbor 192.0.2.5 activate
		neighbor 192.0.2.10 activate

		network 203.0.113.2/32
	exit-address-family

	! IPv6 config
	address-family ipv6 unicast
		neighbor 192.0.2.5 activate
		neighbor 192.0.2.10 activate

		network aa:2::/32
	exit-address-family

exit

segment-routing
srv6
	locators
		locator panbgp
		prefix aa:2::/32
exit
