# Tier 1 connections
as1[0]="A"
as2[0]="A"

# Tier 1 to Tier 2 connections
as1[1]="B"
as3[0]="B"
as4[0]="B"

as2[1]="C"
as4[1]="C"
as5[0]="C"

# Tier 2 to Tier 3 connections
as3[1]="D"
as6[0]="D"
as7[0]="D"

as4[2]="E"
as7[1]="E"

as5[1]="F"
as8[0]="F"
as9[0]="F"

# Tier 3 AS prefixes
as6[1]="H"
as6[2]="I"

as7[2]="J"
as7[3]="K"

as8[1]="L"
as8[2]="M"

as9[1]="N"
as9[2]="O"

# Controller to ASes connections
controller[0]="ctl"
as6[3]="ctl"
as7[4]="ctl"
as8[3]="ctl"
as9[3]="ctl"

# Images
as1[image]="kathara/frr"
as2[image]="kathara/frr"
as3[image]="kathara/frr"
as4[image]="kathara/frr"
as5[image]="kathara/frr"

as6[image]="panbgp/node"
as7[image]="panbgp/node"
as8[image]="panbgp/node"
as9[image]="panbgp/node"

controller[image]="panbgp/controller"
