log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out

router bgp 8
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.41 remote-as 5
	network 198.51.100.40/29
	network 198.51.100.32/29
