log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out

router bgp 6
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.25 remote-as 3
	network 198.51.100.0/29
	network 198.51.100.8/29
