!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!

router bgp 5

	! disable requirement of filtering policy
	no bgp ebgp-requires-policy
	no bgp network import-check

	! declare neighboring AS
	neighbor dd04::1 remote-as 4
	neighbor dd05::2 remote-as 3

	! IPv6 config
	address-family ipv6 unicast
		neighbor dd04::1 activate
		neighbor dd05::2 activate

		network aa05::/16
	exit-address-family

exit


segment-routing
srv6
	locators
		locator panbgp
		prefix aa05::/16

exit
