!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!

router bgp 5
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.21 remote-as 4
	neighbor 192.0.2.25 remote-as 3
	network 203.0.113.5/32
