log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out


router bgp 1

	no bgp ebgp-requires-policy

	! declare neighboring AS
	neighbor 192.0.2.6 remote-as 2
	neighbor 192.0.2.18 remote-as 4

	! IPv4 config
	address-family ipv4 unicast
		neighbor 192.0.2.6 activate
		neighbor 192.0.2.18 activate

		network 192.0.2.0/30
		network 203.0.113.1/32
	exit-address-family

	! IPv6 config
	address-family ipv6 unicast
		neighbor 192.0.2.6 activate
		neighbor 192.0.2.18 activate

		network aa:1::/32
	exit-address-family

exit


segment-routing
srv6
	locators
		locator panbgp
		prefix aa:1::/32
exit
