log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out


router bgp 1

	no bgp ebgp-requires-policy
	no bgp network import-check

	! declare neighboring AS
	neighbor dd01::2 remote-as 2
	neighbor dd03::2 remote-as 4

	! IPv6 config
	address-family ipv6 unicast
		neighbor dd01::2 activate
		neighbor dd03::2 activate

		network af01::/16
		network aa01::/16
	exit-address-family

exit

segment-routing
srv6
	locators
		locator panbgp
		prefix aa01::/16
exit
