# as-to-as lower branch
as1[1]="B"
as2[0]="B"

as2[1]="C"
as6[0]="C"

as6[1]="I"
as3[0]="I"

# as-to-as upper branch
as1[2]="E"
as4[0]="E"

as4[1]="F"
as5[0]="F"

as5[1]="G"
as3[2]="G"

# host to as
h1[0]="A"
as1[0]="A"

h2[0]="D"
as3[1]="D"

# as to controller
as1[3]="H"
as3[3]="H"
controller[0]="H"


h1[image]="kathara/base"
h2[image]="kathara/base"

# Controlled nodes
as1[image]="panbgp/node"
as3[image]="panbgp/node"

as2[image]="kathara/frr"
as4[image]="kathara/frr"
as5[image]="kathara/frr"
as6[image]="kathara/frr"

controller[image]="panbgp/controller"
