!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!

router bgp 4 
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.17 remote-as 1
	neighbor 192.0.2.22 remote-as 5
