!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!

router bgp 4

	bgp router-id aa04::1
	! disable requirement of filtering policy
	no bgp ebgp-requires-policy
	no bgp network import-check

	! Define neighboring AS
	neighbor dd03::1 remote-as 1
	neighbor dd04::2 remote-as 5

	! IPv6 config
	address-family ipv6 unicast
		neighbor dd03::1 activate
		neighbor dd04::2 activate

		network aa04::/16
	exit-address-family

exit


segment-routing
srv6
	locators
		locator panbgp
		prefix aa04::/16

exit
