# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import controller_pb2 as controller__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerMessagingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendASInfo = channel.unary_unary(
                '/ControllerMessagingService/SendASInfo',
                request_serializer=controller__pb2.ASInfo.SerializeToString,
                response_deserializer=controller__pb2.ResponseStatus.FromString,
                _registered_method=True)
        self.RequestPath = channel.unary_unary(
                '/ControllerMessagingService/RequestPath',
                request_serializer=controller__pb2.Destination.SerializeToString,
                response_deserializer=controller__pb2.ASPath.FromString,
                _registered_method=True)


class ControllerMessagingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendASInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerMessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendASInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendASInfo,
                    request_deserializer=controller__pb2.ASInfo.FromString,
                    response_serializer=controller__pb2.ResponseStatus.SerializeToString,
            ),
            'RequestPath': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPath,
                    request_deserializer=controller__pb2.Destination.FromString,
                    response_serializer=controller__pb2.ASPath.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ControllerMessagingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ControllerMessagingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerMessagingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendASInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControllerMessagingService/SendASInfo',
            controller__pb2.ASInfo.SerializeToString,
            controller__pb2.ResponseStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ControllerMessagingService/RequestPath',
            controller__pb2.Destination.SerializeToString,
            controller__pb2.ASPath.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
