log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out

router bgp 1
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.2 remote-as 2
	neighbor 192.0.2.10 remote-as 3
	neighbor 192.0.2.11 remote-as 4
