# This is a modification of one of the labs provided in
# the kathara tutorials.

router1[0]="A"
router1[1]="B"
router1[image]="panbgp/node"

router2[0]="A"
router2[1]="C"
router2[image]="panbgp/node"

controller[0]="D"
router1[2]="D"
router2[2]="D"
controller[image]="panbgp/controller"
