[main]
controller_address = "198.51.100.254"
controller_port = 50051
identity_prefix = "203.0.113.5/32"

[interactive_interface]
address = "127.0.0.1"
port = 9999

[logging]
file = "/var/log/panbgp.log"
level = "debug"
