h1[0]="A"
as1[0]="A"

as1[1]="B"
as2[0]="B"

as2[1]="C"
as3[0]="C"

as3[1]="D"
h2[0]="D"

as1[2]="E"
as4[0]="E"

as4[1]="F"
as5[0]="F"

as3[2]="G"
as5[1]="G"

h1[image]="kathara/base"
h2[image]="kathara/base"

as1[3]="H"
as3[3]="H"
as5[2]="H"
controller[0]="H"

as1[image]="panbgp/node"
as2[image]="kathara/frr"
as3[image]="panbgp/node"
as4[image]="kathara/frr"
as5[image]="panbgp/node"
controller[image]="panbgp/controller"
