h1[0]="A"
as1[0]="A"

as1[1]="B"
as2[0]="B"

as2[1]="C"
as3[0]="C"

as3[1]="D"
h2[0]="D"

as1[2]="E"
as4[0]="E"

as4[1]="F"
as5[0]="F"

as3[2]="G"
as5[1]="G"

as1[image]="kathara/frr"
as2[image]="kathara/frr"
as3[image]="kathara/frr"
as4[image]="kathara/frr"
as5[image]="kathara/frr"
