# Host to AS connections
h1[0]="A"
as1[0]="A"

as3[1]="D"
h2[0]="D"

# AS to AS connections

as1[1]="B"
as2[0]="B"

as2[1]="C"
as3[0]="C"

as1[2]="E"
as4[0]="E"

as4[1]="F"
as5[0]="F"

as3[2]="G"
as5[1]="G"

h1[image]="kathara/base"
h2[image]="kathara/base"

# AS to controller connections
controller[0]="H"
as1[3]="H"
as2[2]="H"
as3[3]="H"
as4[2]="H"
as5[2]="H"

# Images:
# ASes that do NOT want to communicate with the controller
# do not have to run `systemctl start panbgpd_node`

as1[image]="panbgp/node"
as2[image]="panbgp/node"
as3[image]="panbgp/node"
as4[image]="panbgp/node"
as5[image]="panbgp/node"
controller[image]="panbgp/controller"
