!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 3
	no bgp ebgp-requires-policy
	! Define neighboring AS
	neighbor 192.0.2.9 remote-as 2
	neighbor 192.0.2.26 remote-as 5
	! Announcing subnet to neighbors
	network 192.0.2.12/30
