!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 3

	! disable requirement of filtering policy
	no bgp ebgp-requires-policy
	no bgp network import-check

	! declare neighboring AS
	neighbor dd02::1 remote-as 2
	neighbor dd05::1 remote-as 5

	! IPv6 config
	address-family ipv6 unicast
		neighbor dd02::1 activate
		neighbor dd05::1 activate

		network af03::/16
		network aa03::/16
	exit-address-family

exit


segment-routing
srv6
	locators
		locator panbgp
		prefix aa03::/16

exit
