# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\"\x19\n\x06\x41SList\x12\x0f\n\x07\x61s_list\x18\x01 \x03(\r\" \n\x0eResponseStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2L\n\x1a\x43ontrollerMessagingService\x12.\n\x10SendNeighborsASN\x12\x07.ASList\x1a\x0f.ResponseStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASLIST']._serialized_start=20
  _globals['_ASLIST']._serialized_end=45
  _globals['_RESPONSESTATUS']._serialized_start=47
  _globals['_RESPONSESTATUS']._serialized_end=79
  _globals['_CONTROLLERMESSAGINGSERVICE']._serialized_start=81
  _globals['_CONTROLLERMESSAGINGSERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
